name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'jasonfritsche'
        reponame: 'crazyplantperson'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_apiKey: ${{ secrets.VUE_APP_apiKey }}
        VUE_APP_authDomain: ${{ secrets.VUE_APP_authDomain }}
        VUE_APP_projectId: ${{ secrets.VUE_APP_projectId }}
        VUE_APP_storageBucket: ${{ secrets.VUE_APP_storageBucket }}
        VUE_APP_messagingSenderId: ${{ secrets.VUE_APP_messagingSenderId }}
        VUE_APP_appId: ${{ secrets.VUE_APP_appId }}
        VUE_APP_measurementId: ${{ secrets.VUE_APP_measurementId }}
